// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package zz

import (
	"fmt"

	"zombiezen.com/go/sqlite"
)

type InvoiceDeleteRowsStmt struct {
	stmt *sqlite.Stmt
}

func InvoiceDeleteRows(tx *sqlite.Conn) *InvoiceDeleteRowsStmt {
	// Prepare the statement into connection cache
	stmt := tx.Prep(`
delete from invoice_rows where invoice_id = ?1
    `)
	ps := &InvoiceDeleteRowsStmt{stmt: stmt}
	return ps
}

func (ps *InvoiceDeleteRowsStmt) Run(
	invoiceId int64,
) (
	err error,
) {
	defer ps.stmt.Reset()

	// Bind parameters
	ps.stmt.BindInt64(1, invoiceId)

	// Execute the query
	if _, err := ps.stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute invoicedeleterows SQL: %w", err)
	}

	return nil
}

func OnceInvoiceDeleteRows(
	tx *sqlite.Conn,
	invoiceId int64,
) (
	err error,
) {
	ps := InvoiceDeleteRows(tx)

	return ps.Run(
		invoiceId,
	)
}
