// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package zz

import (
	"fmt"

	"zombiezen.com/go/sqlite"
)

type SettingsDeleteAllStmt struct {
	stmt *sqlite.Stmt
}

func SettingsDeleteAll(tx *sqlite.Conn) *SettingsDeleteAllStmt {
	// Prepare the statement into connection cache
	stmt := tx.Prep(`
delete from settings
    `)
	ps := &SettingsDeleteAllStmt{stmt: stmt}
	return ps
}

func (ps *SettingsDeleteAllStmt) Run() (
	err error,
) {
	defer ps.stmt.Reset()

	// Execute the query
	if _, err := ps.stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute settingsdeleteall SQL: %w", err)
	}

	return nil
}

func OnceSettingsDeleteAll(
	tx *sqlite.Conn,
) (
	err error,
) {
	ps := SettingsDeleteAll(tx)

	return ps.Run()
}
