// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package zz

import (
	"fmt"

	"zombiezen.com/go/sqlite"

	"time"

	"github.com/delaneyj/toolbelt"
)

type UserByIdRes struct {
	Id          int64     `json:"id"`
	Uuid        string    `json:"uuid"`
	Username    string    `json:"username"`
	Password    string    `json:"password"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	ConfirmedAt time.Time `json:"confirmed_at"`
	DeletedAt   time.Time `json:"deleted_at"`
}

type UserByIdStmt struct {
	stmt *sqlite.Stmt
}

func UserById(tx *sqlite.Conn) *UserByIdStmt {
	// Prepare the statement into connection cache
	stmt := tx.Prep(`
SELECT
    id, uuid, username, password, created_at, updated_at, confirmed_at, deleted_at
FROM
    users
WHERE
    id = ?1
    `)
	ps := &UserByIdStmt{stmt: stmt}
	return ps
}

func (ps *UserByIdStmt) Run(
	id int64,
) (
	res *UserByIdRes,
	err error,
) {
	defer ps.stmt.Reset()

	// Bind parameters
	ps.stmt.BindInt64(1, id)

	// Execute the query
	if hasRow, err := ps.stmt.Step(); err != nil {
		return res, fmt.Errorf("failed to execute {{.Name.Lower}} SQL: %w", err)
	} else if hasRow {
		row := UserByIdRes{}
		row.Id = ps.stmt.ColumnInt64(0)
		row.Uuid = ps.stmt.ColumnText(1)
		row.Username = ps.stmt.ColumnText(2)
		row.Password = ps.stmt.ColumnText(3)
		row.CreatedAt = toolbelt.JulianDayToTime(ps.stmt.ColumnFloat(4))
		row.UpdatedAt = toolbelt.JulianDayToTime(ps.stmt.ColumnFloat(5))
		row.ConfirmedAt = toolbelt.JulianDayToTime(ps.stmt.ColumnFloat(6))
		row.DeletedAt = toolbelt.JulianDayToTime(ps.stmt.ColumnFloat(7))
		res = &row
	}

	return res, nil
}

func OnceUserById(
	tx *sqlite.Conn,
	id int64,
) (
	res *UserByIdRes,
	err error,
) {
	ps := UserById(tx)

	return ps.Run(
		id,
	)
}
